### ISSUE TITLE
Lightbox Feature Request

### ISSUE THREAD

**Issue by quadsurf** [allpwrfulroot/yaba-social#2]
I see this feature common in other navigation libraries (like wix's react-native-navigation lib, or react-native-router-flux), so I was a bit disappointed to not see it naturally supported in the react-navigation lib.

A few examples of a lightbox modal:
https://github.com/react-native-community/react-native-modal
https://github.com/maxs15/react-native-modalbox

I can easily achieve this lightbox-style “modaling” with the 2 example libs just-mentioned, however, the big problem is that they are controlled by state rather than by navigation on stack (the better way).

A proper lightbox-style modal should behave more like a drawer or side-nav overlay that’s loaded onto stack, where it overlays on top of another screen but the screen underneath it is still visible (but darkened out a bit).

This should probably be more of a PR submitted to the react-navigation lib though, but if you know how to do it, I think it'd be a huge help... I've seen this feature requested several times in their Issues tab.

If I had the expertise to PR this, I gladly would, but I'm just not there yet. Please forgive.

**Comment by allpwrfulroot** [comment]
Thanks for the info! I see the examples but I'm not understanding why a stack is necessarily a "better" way than state for a modal-like screen. Usually anything modal-like just serves as a temporary view, often with an input tied to the underlying view's state anyway? But.

I think you can also get a similar effect with react-navigation. You'll notice that the modal I've included here, the Events filter, is a little unusual: it's a separate Stack with `headerMode: 'none'` and `mode: 'modal'` that is then put into the main Tabs (it felt very clever, since it shows how you can modify a tab's header through a sub-Stack).

You should be able to get a full modal effect by having the Stack with `mode: 'modal'` wrapping the Tabs instead of the other way around and setting all potential backgrounds to transparent? Of course, that might require some experimentation since you might not want all of the other screens to also have the modal behavior. Some ridiculous layering might be required. But since underlying screens aren't being unmounted, I don't see why it wouldn't work...

I'm in the middle of an app launch but if I have the time in the next week I'll experiment.

**Comment by allpwrfulroot** [comment]
Modal example is as complete as it's going to get for now, closing.
